### ISSUE TITLE
Waiting for response in view, but internal 500 error

### ISSUE THREAD

**Issue by kmh005** [MaayanLab/TargetRanger#7]
Hi,

This tool looks really promising.

I'm uploading a 985kb csv as in the example, first column genes with header missing, then 22 samples with headers, by 25079 rows. When clicking the upload button, the view shows that it is waiting for response and never progresses, but upon inspection, the following errors are in the console:

```
Failed to load resource: the server responded with a status of 500 ()
```
```
targetranger.maayanlab.cloud/:1 Uncaught (in promise) SyntaxError: Unexpected token 'I', "Internal S"... is not valid JSON
```

Can you please advise?

Thanks,
kmh005

**Comment by u8sand** [comment]
Hi @kmh005 -- thank you for reporting this.

I can't be certain what the issue is without the file but it seems the parsing is somehow not working.

My best wild guess is that it could be related to line-endings if you were using Windows.

I've patched this particular issue but if that doesn't fix it, it would be helpful to see your file so I can test it (at least partially, maybe just the first 5 rows & columns or something).

**Comment by kmh005** [comment]
Hello,

Thanks for your speedy response.

The file was generated on unix, saved by write.csv in RStudio.

Here's the first 5 rows, this also has a hung view.

[pseudo_for_targetranger.csv](https://github.com/MaayanLab/TargetRanger/files/11265520/pseudo_for_targetranger.csv)

Thanks for your help!

**Comment by u8sand** [comment]
Hi! Thank you for providing this. It seems the issue is likely a misalignment with the gene symbols.

The current conversion mechanism isn't spectacularly sophisticated but it is based on mapping with Entrez Gene. It should also work with ensembl stable ids (i.e. ENSG00..) at the **protein coding** gene level.

The symbols I got from you look like non-coding genes so you might need to stick with transcripts, we may consider including non-protein coding genes in the future. For transcripts, we're expecting Ensembl transcript ids (i.e. ENST00..)

**Comment by kmh005** [comment]
Hi again,

Ok I see what you're getting at, and understand the limitations.

I removed all genes with no Entrez/Ensembl annotation, as well as took out the LINC, orf, and hyphenated gene names. I'm using org.Hs.eg.db version 3.15.0 for these manipulations. I'm still not having luck with the upload. I've tried both HGNC and Ensembl identifiers.

Here's 2 columns of data, HGNC. Are there any other identifiers that the converter can't handle that I'm missing?

[pseudo_for_targetranger_gs_only.csv](https://github.com/MaayanLab/TargetRanger/files/11266332/pseudo_for_targetranger_gs_only.csv)


Thanks,
kmh005

**Comment by giacomomarino** [comment]
Hello,

It looks to me that there are quotation marks in your counts file surrounding the gene names. If you remove these:
[pseudo_for_targetranger_gs_only.csv](https://github.com/MaayanLab/TargetRanger/files/11266546/pseudo_for_targetranger_gs_only.csv) you should receive results (though I didn't see any targets based on these counts). Hope this helps and let us know if you have any more issues.
